resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/bardec/flight-school
    branch: master

- name: heroku-app
  type: git
  source:
    uri: ssh://git@heroku.com/flight-school-fraud-tools.git
    branch: master
    private_key: ((heroku_private_key))

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml
  - put: heroku-app
    params:
      repository: flight-school
